### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by ericjiang97** [ericjiang97/ericjiang.dev#2]
- Requested by @nchlswhttkr

**Comment by nchlswhttkr** [comment]
[![Binny bleese](https://booru.vineshroom.net/_images/ccd66b97b94c133782b72546b8fb65f6/77077%20-%20DevilMayCry%20artist%3AMurphio%20meat%20scoot%20streamer%3Avinny.png)](https://www.youtube.com/watch?v=GyeovGS-EU4)

**Comment by nchlswhttkr** [comment]
It is bedtime Eric, you should call it a night

**Comment by nchlswhttkr** [comment]
This is now showing up on my news feed Eric what have you done

**Comment by ericjiang97** [comment]
Dark theme is now default. Light theme is not available
